#!/bin/bash

export TERM=screen-24bit

if [ $# -eq 0 ]; then
    if pgrep -i emacs; then
        DISPLAY= emacsclient -c
    else
        nano
    fi
else 
    pgrep -i emacs && emacsclient "$@" || nano "$@"
fi
